#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Для того чтобы до пуша проверять все ли у нас корректно и потом неисправлять ошибки после пуша и прохода пайплацна и плодить новые коммиты
npm run build:prod
npm run lint:ts
npm run lint:scss
npm run test:unit
npm run storybook:build
npm run test:ui
