name: Linting, Testing, Building
# В каких моментах должны запускаться пайплайны (пуш, пр)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    # OS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    # Шаги/этапы пайплайна
    steps:
      # Базовые настройки для пайп этапов
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Дальше запускаем сами этапы и скрипты
      - name: install dependencies
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting styles
        run: npm run lint:style
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        run: npm run test:ui:ci

